Task 1: add architecture description
ProgMiner/Lab_SoftwareDevelopment pull request #1
Opened 2023-02-20 19:55 UTC by ProgMiner

2023-02-20 19:58 UTC, ilyaivantsov commented
Збс!

2023-02-26 13:13 UTC, uncerso requested changes
Нужно больше подробностей. 

Помимо точечных комментариев плохо описаны команды. Как они работают, что принимают на вход и что делают, если их ожидания нарушены, как ведут себя с потоками ввода-вывода, что по кодам возврата.

2023-02-26 13:13 UTC, uncerso commented on README.md
> +```
А можно всё же увидеть диаграмму классов? Вот вам в помощь: [https://www.uml-diagrams.org/class-diagrams-overview.html](url)
Вам понадобятся: класс, интерфейс, композиция, агрегация, зависимость (особенно Usage). И всё, этого вам хватит с головой.

Входные и выходные аргументы вы прекрасно можете выразить через методы с этими самыми аргументами.

2023-02-26 13:13 UTC, uncerso commented on README.md
> +- Флаг работы -- булев флаг, определяющий, продолжается ли работа приложения
И эти поля тоже хорошо бы отразить на диаграмме классов.

2023-02-26 13:13 UTC, uncerso commented on README.md
> +состоящей из нескольких команд.
А как же поток stderr? Внешние команды с радостью в него пишут.

2023-02-26 13:13 UTC, uncerso commented on README.md
> +обработки.
А зачем брать ненужные символы? У вас есть критерий, по которому вы разбиваете входной текст на куски, которые обрабатываете. И заключён он во фразе "считывает его первую строку".

2023-02-26 13:13 UTC, uncerso commented on README.md
> +#### Parser
А немного ли работы на себя берёт парсер? Как минимум читать входной поток, выполнять подстановки, собирать команды -- это три независимые логики. И вот на этом месте где-то в угу плачет принцип единственности ответственности из SOLID.

2023-02-26 13:13 UTC, uncerso commented on README.md
> +При старте программы запускается цикл, итерирующийся пока флаг работы из состояния установлен в
```suggestion
При старте программы запускается цикл, итерирующийся, пока флаг работы из состояния установлен в
```

2023-02-26 13:13 UTC, uncerso commented on README.md
> +При старте программы запускается цикл, итерирующийся пока флаг работы из состояния установлен в
Ну и лучше уже как-то назвать разумно этот "флаг работы из состояния". Что-нибудь типа `shutdown` или `exitRequested`, или `needProcessNextUserInput`. И ссылаться на него по этому названию.

2023-02-26 13:13 UTC, uncerso commented on README.md
> +остальным модулям.
А лучше вынести в отдельный модуль, чтобы не смешивать его с точкой входа приложения. И тестировать будет проще.

2023-02-26 13:13 UTC, uncerso commented on README.md
> +Строка с подставленными переменными возвращается как результат работы функции
Я же правильно понимаю, что сначала находятся все места подстановок в текущей строке, затем эти найденные подстановки "разом" выполняются, и дальше строка возвращается?

2023-02-26 13:13 UTC, uncerso commented on README.md
> +запускается специальная функция, которая подставляет переменные из окружения
То есть команда `meow=woof; echo '"$meow"'` выведет woof несмотря на то, что весь аргумент в одинарных кавычках?

2023-02-26 13:13 UTC, uncerso commented on README.md
> +каждой команды в пайплайне формируется отдельный список)
А по пробельным символам вновь не разрезаний не происходит? Получается, что команда `x='echo 123'; $x` завершится ошибкой?

2023-02-26 13:13 UTC, uncerso commented on README.md
> +#### Объекты команд
Не забудьте их все на диаграмме отразить.

2023-02-26 13:13 UTC, uncerso commented on README.md
> +- `cd` -- изменяет текущую рабочую директорию (значение переменной окружения `PWD`)
Не надо её сейчас реализовывать. Её нет в списке текущих команд, которые нужно поддержать, и её реализация будет неожиданным для вас образом связана с другой домахой.

2023-02-28 11:39 UTC, ProgMiner commented on README.md
> +```
По заданию не нужно было рисовать диаграмму классов, потому что мы на момент выполнения ещё не проходили UML:
> Результатом должна являться структурная диаграмма (например, диаграмма классов UML — пока как умеете)

Юрий прокомментировал, что приведённой диаграммы достаточно по заданию

2023-02-28 11:39 UTC, ProgMiner commented on README.md
> +состоящей из нескольких команд.
Спасибо, забыли про него.

2023-02-28 11:40 UTC, ProgMiner commented on README.md
> +обработки.
При считывании строки из потока ввода невозможно гарантировать, чтобы была прочитана ровно одна строка. Поэтому необходимо гарантировать возможность вернуть лишние символы, находящиеся после символа перевода строки, обратно в поток, чтобы ими могла воспользоваться команда.

2023-02-28 11:44 UTC, ProgMiner commented on README.md
> +#### Parser
Принцип единственности ответственности здесь не нарушается. Парсеру необходимо самостоятельно выбрать, куда можно подставлять значения переменных (то есть произвести некоторый разбор строки), затем подставить значения переменных, а уже после этого произвести окончательный разбор строки. Нет смысла разделять два разбора строки, непосредственно связанных между собой семантически, на несколько компонентов.
Конструирование команд намного более удобно будет реализовать как часть парсера в проекте такого масштаба. В частности, потому что некоторые из команд являются служебными и не поддаются обычным правилам формирования команд. Например, команда конвейера, установки значения переменной и вызова внешнего процесса.

2023-02-28 11:47 UTC, ProgMiner commented on README.md
> +остальным модулям.
Да, лучше вынести. В данном случае было принято такое решение, чтобы не уносить обработку ошибок слишком далеко от непосредственного логического места, где они должны быть обработаны. В частности, это позволит более просто согласовывать эффекты обработки ошибок с главным циклом работы программы.

2023-02-28 11:47 UTC, ProgMiner commented on README.md
> +Строка с подставленными переменными возвращается как результат работы функции
Да, на практике по этому заданию Юрий отдельно обращал внимание на то, что необходимо делать именно так.

2023-02-28 11:49 UTC, ProgMiner commented on README.md
> +запускается специальная функция, которая подставляет переменные из окружения
В данном случае должно быть выведено `'"$meow"'`, потому что строка находится в первую очередь в одинарных кавычках, а уже во вторую -- в двойных. Поэтому наличие двойных кавычек будет проигнорировано, в соответствии с тем, как работают одинарные кавычки (позволяют писать внутри всё что угодно, кроме одинарных кавычек, и, может быть, символа перевода строки, без дополнительных эффектов).

2023-02-28 11:50 UTC, ProgMiner commented on README.md
> +каждой команды в пайплайне формируется отдельный список)
Не происходит. Это не требуется напрямую в задании. Более того, несмотря на то, что bash позволяет так делать, zsh, например, не позволяет. Юрий отдельно прокомментировал, что это допустимое поведение.

2023-02-28 11:53 UTC, ProgMiner commented
> что по кодам возврата

В задании нигде не написано, что мы должны хоть что-то знать о кодах возврата. Нет требования специальной переменной `$?` или какого-либо специального поведения в ответ на ненулевой код возврата.

2023-03-18 19:58 UTC, uncerso commented on README.md
> +запускается специальная функция, которая подставляет переменные из окружения
А одинарные кавычки не отбросились?

Вообще тут имеется ввиду неаккуратность фразы "(вне кавычек и в двойных кавычках)", ибо формально `'"$meow"'` находится как в одинарных, так и двойных кавычках.

2023-06-18 11:58 UTC, merged