Roguelike, implementation part 4
ProgMiner/Lab_SoftwareDevelopment pull request #10
Opened 2023-06-07 04:58 UTC by ProgMiner

- [x] Реализация @ProgMiner 
- [x] Комментарии с документацией @ProgMiner 
- [ ] Unit-тесты @ilyaivantsov 
- [ ] CI @ilyaivantsov 
- [ ] Диздок

В качестве допзадания реализована стратегия https://github.com/ProgMiner/Lab_SoftwareDevelopment/blob/2001fbd94035d79944be3551a3df7d8b1daa3333/src/game/behaviour/EnhancedAggressiveBehaviourModel.ts#L19, реализующая шаблон проектирования Состояние с 4 состояниями, не входящими в основное задание.

2023-06-13 22:25 UTC, uncerso requested changes
А вы знали, что при загрузке карты из файла нельзя использовать один и тот же индекс несколько раз (т.е. если "2. Item GoldenApple", то 2 можно поставить только один раз, иначе все, кроме последнего, будут проигнорированы)? Это из формата выглядит контринтуитивно.

Если что, комментарии здесь не требуется править, это некритичные моменты, которые не оцениваются. Вернее оценивались бы, если бы вы жесть какую-нибудь накодили, а так всё здорово. Вы внезапно по всем критериям попали в яблочко (что немного подозрительно, ага), остаётся только тесты доделать.

Почти всё ревью сделал в понедельник, немного с бидлерами не успел только, поэтому сейчас фидбэк тоже на основании не самой свежей версии. Дифф посмотрю позже, быть может, когда сами посчитаете, что тесты готовы.

2023-06-13 22:25 UTC, uncerso commented on src/core/events/ClickEvent.ts
> +export type ClickEvent = DomEvent<'click', MouseEvent>;
Ага! А в диздоке заявлялось, что нужна только клавиатура!

2023-06-13 22:25 UTC, uncerso commented on src/utils/Coordinates.ts
> +    }
Всё же норма -- это число. А вы нормированный вектор возвращаете. Так что скорее normalized метод должен называться.

2023-06-13 22:25 UTC, uncerso commented on src/utils/Coordinates.ts
> +    }
Интересно, есть ли способ подсократить копипасту.

2023-06-13 22:25 UTC, uncerso commented on src/utils/Coordinates.ts
> +        return this.x === that.x && this.y == that.y;
А почему в одном случае `===`, а в другом `==`?

2023-06-13 22:25 UTC, uncerso commented on src/utils/drawBar.ts
> +    context.fillRect(center.x - size.x / 2, center.y - size.y / 2, size.x, size.y);
Не очень классно 10 раз писать  такую сложную строку. Легко случайно опечататься и поставить x вместо y. Я бы, наверное, расширил контекст своими методами, которые принимают center и size и делают то, что тут написано.

2023-06-13 22:25 UTC, uncerso commented on src/game/Wall/Wall.ts
> +        let minDistance: number;
Какое-то безумие с вычислением этого значения. Я так и не понял, почему тут есть какие-то width и height.

Можете словами описать, что вы хотели здесь сделать?

2023-06-13 22:25 UTC, uncerso commented on src/core/handlers/GameInterfaceEventHandler.ts
> +const HEALTH_BAR_ANIMATION_SPEED = 0.01; // 1/ms
1/ms? Быть может px/ms? Или что такое 1?

2023-06-13 22:25 UTC, uncerso commented on src/core/handlers/LevelUpEventHandler.ts
> +const LEVEL_UP_SCREEN_TIME = 2000;
А не думали воспользоваться какой-нибудь библиотекой, которая нормальное типизированное время предоставляет, а просто чиселко?

2023-06-13 22:25 UTC, uncerso commented on src/states/GameState.ts
> +    darknessRadius: number;
Единицы измерения?

2023-06-13 22:25 UTC, uncerso commented on src/states/GameState.ts
> +    updateDistance: number;
Единицы измерения?

2023-06-13 22:25 UTC, uncerso commented on src/game/mobs/AbstractMob.ts
> +        TemporalBehaviourModel.decorate(this, CONFUSION_STEPS, new ChaoticBehaviourModel());
А не получится, что мы настакаем цепочку из временных хаотичных состояний?

2023-06-13 22:25 UTC, uncerso commented on src/game/mobs/AbstractMob.ts
> +        TemporalBehaviourModel.decorate(this, CONFUSION_STEPS, new ChaoticBehaviourModel());
Видимо из-за CONFUSION_STEPS == 1 не получится. Но если сделать 2 -- уже проблемы будут.

2023-06-13 22:25 UTC, uncerso commented on src/core/handlers/MainMenuEventHandler.ts
> +        [new TechnoMobGenerator({ Robot: 2 }), 2],
А для чего отдельно отдавать суммы элементов (7 у MagicalMobGenerator и 2 у TechnoMobGenerator)?

2023-06-13 22:25 UTC, uncerso commented on src/game/generators/Generator.ts
> +    generate(random: Random): Promise<T>;
Схалтурили немного. :)
Хотелось бы несколько таких методов (хотя бы generateWeak и generateStrong), а то бедная какая-то фабрика получилась. Ну да ладно, принцип вы поняли, так что пойдёт.

2023-06-13 23:32 UTC, ProgMiner commented on src/core/events/ClickEvent.ts
> +export type ClickEvent = DomEvent<'click', MouseEvent>;
Эта штука в итоге нигде не используется. Чесались руки сделать полноценную UI библиотеку хотя бы чтобы сделать кнопки в главном меню по нажатию, но не получилось. Это, кстати, единственное место, где пришлось реально выкинуть кучу кода, на которую было потрачено много времени.

2023-06-13 23:33 UTC, ProgMiner commented on src/utils/Coordinates.ts
> +    }
Справедливо. Я просто не очень силён в геометрии и в английском =)

2023-06-13 23:33 UTC, ProgMiner commented on src/utils/Coordinates.ts
> +    }
Вообще есть, но тогда TypeScript почти наверное не поймёт тип, хотя я честно не пробовал.

2023-06-13 23:35 UTC, ProgMiner commented on src/utils/Coordinates.ts
> +        return this.x === that.x && this.y == that.y;
Опечатка, спасибо

2023-06-13 23:37 UTC, ProgMiner commented on src/utils/drawBar.ts
> +    context.fillRect(center.x - size.x / 2, center.y - size.y / 2, size.x, size.y);
IMHO, то что влезает в одну строку (по ограничению IDE) — не сложно. Да и тут довольно очевидные значения написаны. В других местах я выделяю в переменные такие вещи

2023-06-13 23:42 UTC, ProgMiner commented on src/game/Wall/Wall.ts
> +        let minDistance: number;
Здесь сложность в том, что у нас есть прямоугольник шириной width и высотой height, ориентированный по координатной сетке, и координаты его левого верхнего угла (как прописано в документации). А также у нас есть позиция игрока. Требуется найти расстояние от точки до прямоугольника, при том что точка расположена вне прямоугольника.

Реализованное решение разбивает координатную сетку на 9 частей, проводя 4 прямых: две вертикальные и две горизонтальные, по сторонам прямоугольника. Середина не используется, потому что игрок не внутри прямоугольника, а для остальных 8 частей разобраны отдельные случаи с вычислением расстояния от игрока до ближайшей стороны (в 4 случаях), или до ближайшего угла прямоугольника (в остальных 4 случаях).

Согласен, что код нетривиальный, но проще придумать не получилось. Зато на самом деле он наглядный, потому что условные операторы в точности отражают задумку — разбиение плоскости на отдельные части.

2023-06-13 23:44 UTC, ProgMiner commented on src/core/handlers/GameInterfaceEventHandler.ts
> +const HEALTH_BAR_ANIMATION_SPEED = 0.01; // 1/ms
Анимация движется не по пикселям, а по долям от ширины health bar'а, по значениям от 0 до 1. Поэтому это не пиксели, а доля, которая не измеряется ни в каких единицах (как вероятность, например). Соответственно, скорость движения значения измеряется в $`ms^{-1}`$

2023-06-13 23:44 UTC, ProgMiner commented on src/core/handlers/LevelUpEventHandler.ts
> +const LEVEL_UP_SCREEN_TIME = 2000;
Кажется, это оверкилл для такого проекта

2023-06-13 23:48 UTC, ProgMiner commented on src/states/GameState.ts
> +    darknessRadius: number;
Пиксели. Спасибо, добавил

2023-06-13 23:49 UTC, ProgMiner commented on src/core/handlers/MainMenuEventHandler.ts
> +        [new TechnoMobGenerator({ Robot: 2 }), 2],
Специфика работы Uniform генератора. Их можно сделать другими, тогда просто вероятность спавна будет другой. Сейчас с вероятностью 7/9 выбирается первый генератор, а с вероятностью 2/9 второй.

2023-06-13 23:50 UTC, ProgMiner commented on src/game/generators/Generator.ts
> +    generate(random: Random): Promise<T>;
А я просто не понял, какие можно разумные методы добавить. Да и сама фабрика тут появилась ещё до задания на фабрику, как тривиальное решение поставленной задачи =)

2023-06-13 23:52 UTC, ProgMiner commented on src/game/mobs/AbstractMob.ts
> +        TemporalBehaviourModel.decorate(this, CONFUSION_STEPS, new ChaoticBehaviourModel());
Не думаю, что это проблема. Ну то есть да, если бы количество шагов до прохода конфузии было бы больше единицы, они бы стакались, это может быть может привести к какому-то излишнему расходу памяти, но с логической точки зрения всё будет правильно, шаги до прохода конфузии будут суммироваться. Да и мне показалось, что такое решение предполагается в задании

2023-06-13 23:55 UTC, ProgMiner commented on src/states/GameState.ts
> +    updateDistance: number;
Казалось очевидным, что количество клеток в координатной сетке мира. Но согласен, что могли быть и пиксели, добавил

2023-06-14 00:02 UTC, ProgMiner commented
> А вы знали, что при загрузке карты из файла нельзя использовать один и тот же индекс несколько раз (т.е. если "2. Item GoldenApple", то 2 можно поставить только один раз, иначе все, кроме последнего, будут проигнорированы)? Это из формата выглядит контринтуитивно.

Ух-ты, я даже не думал о таком варианте использования. Уточню в документации =)

> Вы внезапно по всем критериям попали в яблочко (что немного подозрительно, ага), остаётся только тесты доделать.

Ну задания вполне прозрачно доносят, что от нас требуется, и никаких особых проблем с реализацией не было, кроме разве что придумывания своего конечного автомата (кстати, учитываете ли вы "до +3 бонусных баллов за реализацию дополнительных стратегий и состояний"). Проблема только в объёме работы, но, как говорится, глаза боятся — руки делают. А архитектура эта вся за полчаса придумывается и в голове легко удерживается целиком.

> Дифф посмотрю позже, быть может, когда сами посчитаете, что тесты готовы.

Хорошо, тогда не буду лишний раз дёргать

2023-06-18 12:47 UTC, merged