Task 2: implementation part 1
ProgMiner/Lab_SoftwareDevelopment pull request #2
Opened 2023-03-09 18:10 UTC by ProgMiner

2023-03-19 23:30 UTC, uncerso requested changes
Ещё нужны тесты на сами команды как минимум.

Сломанный вывод ошибки:
```
> cat ''
> Cannot read file: "Is a directory".
```

В остальном неплохо.

2023-03-19 23:30 UTC, uncerso commented on src/main/kotlin/ru/byprogminer/shellin/State.kt
> +            environment[PWD_VARIABLE] = value.absolute().normalize().toString()
Ну что это за грязные хаки.
![image](https://user-images.githubusercontent.com/25592720/226213763-53a7792e-e064-4541-830b-8911e36c56e4.png)

А, главное, что мешало в отдельную переменную положить, а не складывать всё в кучу.

2023-03-19 23:30 UTC, uncerso commented on src/main/kotlin/ru/byprogminer/shellin/Parser.kt
> +            require(buffer.hasRemaining())
Ага.
![image](https://user-images.githubusercontent.com/25592720/226214239-8daf5232-7d1a-4202-b104-753c0be88b95.png)

А если, кстати, без кавычек вводить тучу букв "а", то они просто обрежутся.

2023-03-19 23:30 UTC, uncerso commented on src/main/kotlin/ru/byprogminer/shellin/Parser.kt
> +        var buffer = ByteBuffer.allocate(READ_LINE_BUFFER_SIZE)
Почему вместо вот этого всего не воспользоваться BufferedReader? У него как раз есть метод readLine.

2023-03-19 23:30 UTC, uncerso commented on src/main/kotlin/ru/byprogminer/shellin/command/CdCommand.kt
> +class CdCommand(
Втф. Я же просил не реализовывать эту функцию.
Удалите, пожалуйста, файл полностью и любые его упоминания. Жаль историю не потереть, уже. :(

Из PR следующей домахи тоже не забудьте вырезать её.

2023-03-19 23:30 UTC, uncerso commented on src/test/kotlin/ru/byprogminer/shellin/ParserTest.kt
> +}
Ага, надо бы сделать.

2023-03-20 00:06 UTC, ProgMiner commented on src/main/kotlin/ru/byprogminer/shellin/State.kt
> +            environment[PWD_VARIABLE] = value.absolute().normalize().toString()
Показалось, что так будет более правильно. Зачем нам отдельная переменная, если уже есть хранилище для таких вещей?)

2023-03-20 00:06 UTC, ProgMiner commented on src/main/kotlin/ru/byprogminer/shellin/Parser.kt
> +            require(buffer.hasRemaining())
Не успели пофиксить. Про много букв не проверили, к сожалению.

2023-03-20 00:08 UTC, ProgMiner commented on src/main/kotlin/ru/byprogminer/shellin/Parser.kt
> +        var buffer = ByteBuffer.allocate(READ_LINE_BUFFER_SIZE)
К сожалению, тогда бы ввод забрался из InputStream и остался в буфере. Это бы сработало в большом количестве случаев, когда `read` возвращает только последнюю введённую строку, но при перенаправлении ввода из файла часть ввода была бы съедена, вместо того, чтобы отправиться в команду. Увы, готовых решений для этой проблемы нет в стандартной библиотеке, поиск в интернете давал только что-то похожее на приведённый код.

2023-03-20 00:09 UTC, ProgMiner commented on src/main/kotlin/ru/byprogminer/shellin/command/CdCommand.kt
> +class CdCommand(
:cry:

2023-03-20 00:09 UTC, ProgMiner commented on src/test/kotlin/ru/byprogminer/shellin/ParserTest.kt
> +}
К сожалению, не успели сделать все тесты.

2023-03-26 15:06 UTC, ProgMiner commented on src/main/kotlin/ru/byprogminer/shellin/Parser.kt
> +            require(buffer.hasRemaining())
IAE пофиксил, а вот обрезание не воспроизводится что-то...

2023-03-26 15:15 UTC, ProgMiner commented
> Сломанный вывод ошибки

Это вы, скорее всего, в IDEA запускали. В ней есть некоторая проблема с синхронизацией потоков вывода.
Ошибка пишется в stderr, а приглашение на ввод команды -- в stdout. В обычном терминале всё работает как надо.

2023-03-26 15:42 UTC, ProgMiner commented on src/main/kotlin/ru/byprogminer/shellin/Parser.kt
> +            require(buffer.hasRemaining())
Получилось воспроизвести. Почему-то искуственно вставляется LF на 4095 позиции. Скорее всего из-за этого:
- https://stackoverflow.com/questions/68777744/how-to-input-a-line-longer-than-4095-characters-in-java
- https://stackguides.com/questions/39546500/how-to-make-scanf-to-read-more-than-4095-characters-given-as-input

Если вставлять команду через перенаправление ввода из файла, или через HEREDOC, то всё считывается корректно и ничего не обрезается

2023-04-08 11:21 UTC, uncerso commented on src/main/kotlin/ru/byprogminer/shellin/State.kt
> +            environment[PWD_VARIABLE] = value.absolute().normalize().toString()
Как бы pwd -- это не результат какой-то переменной окружения, а хранилище как раз для для переменных окружения. А смешение мух с котлетами -- это всегда баг.

2023-04-08 11:25 UTC, uncerso commented
> Это вы, скорее всего, в IDEA запускали. В ней есть некоторая проблема с синхронизацией потоков вывода. Ошибка пишется в stderr, а приглашение на ввод команды -- в stdout. В обычном терминале всё работает как надо.

Неа. Вообще сложно запустить IDEA из контейнера, в котором нет ничего про wm, а без окна она врядли заработает. :)

2023-06-07 20:09 UTC, ProgMiner commented
Добавил тесты на все модули. Проверить системные команды на винде и макоси не получилось.
На винде почему то не видит в Path даже cmd, хотя при ручной проверке на реальной системе всё работало, а на макси просто билд зависает в CI.

2023-06-17 11:00 UTC, uncerso approved these changes

2023-06-18 12:02 UTC, merged