Task 3: implementation part 2
ProgMiner/Lab_SoftwareDevelopment pull request #3
Opened 2023-03-13 01:00 UTC by ProgMiner

2023-03-26 23:03 UTC, uncerso requested changes
Тестов нет. А вот ваши коллеги 175 штук за обе домашки придумали. :(

Ну вот.
```
> echo 123 | wc
Usage: wc <FILE>
```
То же самое с cat.

2023-03-27 05:07 UTC, ProgMiner commented
> Тестов нет. А вот ваши коллеги 175 штук за обе домашки придумали. :(

Очень рад за коллег. У меня не хватает сил заставить себя писать тесты, когда я вижу сколько у меня не сделано домашек по другим предметам. Надеюсь, потом они появятся.

По поводу `cat` и `wc` поправлю, просто произошло недопонимание задания.

2023-06-07 20:47 UTC, ProgMiner commented
Исправил команды `cat` и `wc`, влил тесты из предыдущего задания, добавил недостающие тесты

2023-06-17 11:08 UTC, uncerso approved these changes

2023-06-18 12:10 UTC, merged