Task1: architecture notes
ProgMiner/Lab_SoftwareDevelopment pull request #5
Opened 2023-04-09 21:01 UTC by ProgMiner

2023-06-11 22:44 UTC, uncerso requested changes
Типичного пользователья нет. :(

Ещё диаграммы последовательностей и конечных автоматов хочется увидеть.

А так, в целом, неплохо.

2023-06-11 22:44 UTC, uncerso commented on README.md
> +- Система не должна воспроизводить звуки
Технические ограничения не в смысле тех, что накладываются на вашу программу искусственно вами (например, не должна воспроизводить звуки), а в смысле тех, которые в природе существуют, от вас не зависят и мешают сделать вам то, что вы хотите. Например, "браузер, на котором исполняется программа, должен поддерживать WebGL", иначе из браузера никак не получить приемлемый фпс.

2023-06-11 22:44 UTC, uncerso commented on README.md
> +- Разработка системы должна быть завершена к моменту сдачи экзамена (12.06.2023)
А ещё из-за сжатых сроков, например, в технических ограничениях вполне может быть "должен существовать фрэймворк, который делает вот это".

Забавно, что нет цели "закрыть курс с высокой оценкой". Видимо уже хоть как-то хотите сдать, понятно.

2023-06-11 22:44 UTC, uncerso commented on README.md
> +- Должна быть доступна генерация случайного мира и загрузка из файла
В принципе в функциональные требования можно включать некоторые границы систему, но по-факту это немного бессмысленно, ибо при рассмотрении какой-то функциональности надо смотреть на оба списка. Поэтому списки обычно почти не пересекаются.

Поэтому здесь последний пункт хорошо подходит, а два остальных -- ок, но не очень.

----

Описание границ системы -- это то, чем ваша система скорее НЕ должна являться. Т.е. если вдруг такое требование поменяется, то проще будет начать новый проект, чем этот переделывать. 

Функциональные требования -- это то, чем должно являться, что оно вообще должно уметь. 

Т.е. быть в жанре рогалика -- это граница, ибо переделать игру под, скажем, шутер вообще не получится. Пошаговость -- тоже граница, иначе придётся переписать половину проекта в лучшем случае.

"Система не использует звуковое сопровождение, никакие звуки не проигрываются на компьютере в
  связи с использованием системы", т.е. "игра без музыки" -- НЕ граница, ибо добавить музыку -- дело нехитрое. И оно же и НЕ функциональное требование, ибо функциональные требования декларируют то, что надо уметь.

А вот уметь загружаться из файла -- это функциональное требование. 
Например, ещё функциональные требования -- это что управление одним персонажем, что в игре должны быть враги, что есть лут и предметы экипировки, что персонаж может атаковать, что бой происходит автоматически [т.е. на исход боя игрок не может повлиять активно, только через эквип] (это не граница, ибо добавить миниигру хоть и большая задача, но она вполне укладывается в вашу систему и переделки существующего проекта почти не потребует, только новая функциональность добавится).

2023-06-11 22:44 UTC, uncerso commented on README.md
> +
Сюда ещё надо бы добавить "Качественные характеристики системы" и "Нефункциональные требования".

2023-06-11 22:44 UTC, uncerso commented on README.md
> +мир, окружающий персонажа.
Здесь имелось ввиду, что пользователей вашего продукта можно разбить на несколько ролей (один пользователь как человек может быть в нескольких ролях), и в каждой роли пользователь когда-то при некоторых условиях хочет что-то сделать с вашим продуктом. Из этого, в частности, рождаются какие-то требования. Например, роли "игроки" и "дизайнер локаций". Для дизайнера случай использования "хочет просто и быстро создавать новые сложные и интересные уровни, но не хочет копаться в коде", поэтому ваш продукт должен уметь загружать уровни из файла, при этом формат должен быть либо человекочитаемым, либо, например, иметь отдельный графический тул для его редактирования.

2023-06-11 22:44 UTC, uncerso commented on README.md
> +![Диаграмма компонентов](./uml/components.drawio.png)
Несколько неожиданно видеть стрелочки зависимостей прямо из компонента в компонент, минуя порты и коннекторы. Стоит поправить.

2023-06-11 22:44 UTC, uncerso commented on README.md
> +  анимаций и отрисовки кадров,
А если они ну будут успевать обработаться, что будет? Они будут накапливаться и однажды сожрут всю память компьютера?

2023-06-11 22:44 UTC, uncerso commented on README.md
> +- **State** — общий тип для всех состояний конкретного типа.
```suggestion
- **BaseState** — базовый интерфейс для всех типов состояний;
- **GameState** — тип состояния, использующегося во время игры;
- **MainMenuState** — тип состояния, использующегося для главного меню игры;
- **State** — общий тип для всех состояний конкретного типа.
```

2023-06-11 22:44 UTC, uncerso commented on README.md
> +для стен это свойство имеет истинное значение, а для предметов — ложное).
Может наоборот? Кажется, что сквозь стены довольно сложно проходить, вто время как переступить через предмет -- легко.

2023-06-11 22:44 UTC, uncerso commented on README.md
> +![Диаграмма классов компонента Игровая логика](./uml/game_logic_classes.drawio.png)
Довольно странно видеть летающий EquipmentType. Явно напрашивается usage зависимость из Equipment.

2023-06-11 22:44 UTC, uncerso commented on README.md
> +![Диаграмма классов компонента Генератор мира](./uml/world_generator_classes.drawio.png)
File и Boxed world generator'ы видимо реализуют интерфейс WorldGenerator, а не расширяют, поэтому стрелочка должна быть пунктирной.

2023-06-12 03:46 UTC, ProgMiner commented on README.md
> +- Разработка системы должна быть завершена к моменту сдачи экзамена (12.06.2023)
> А ещё из-за сжатых сроков, например, в технических ограничениях вполне может быть "должен существовать фрэймворк, который делает вот это".

Как то без фреймворка обошлось, поэтому чё ж писать об этом...

> Забавно, что нет цели "закрыть курс с высокой оценкой". Видимо уже хоть как-то хотите сдать, понятно.

А вот это неправда, просто неочевидно, что такие вещи тоже пишутся сюда.

2023-06-12 03:51 UTC, ProgMiner commented on README.md
> +  анимаций и отрисовки кадров,
Тут, видимо, стоит добавить, что **TickEvent** должен генерироваться не чаще, чем 60 раз в секунду, чтобы такого не происходило?

2023-06-12 03:53 UTC, ProgMiner commented on README.md
> +для стен это свойство имеет истинное значение, а для предметов — ложное).
Да, тут опечатка, спасибо.

2023-06-12 03:58 UTC, ProgMiner commented on README.md
> +![Диаграмма классов компонента Игровая логика](./uml/game_logic_classes.drawio.png)
Добавил, спасибо

2023-06-12 03:58 UTC, ProgMiner commented on README.md
> +![Диаграмма классов компонента Генератор мира](./uml/world_generator_classes.drawio.png)
Исправил, спасибо

2023-06-12 04:00 UTC, ProgMiner commented
> Типичного пользователья нет. :(

А Роли и случаи использования не покрывают этот пункт?

> Ещё диаграммы последовательностей и конечных автоматов хочется увидеть.

Это будет, просто руки до тех разделов пока не дошли, к сожалению.

2023-06-12 04:11 UTC, ProgMiner commented on README.md
> +![Диаграмма компонентов](./uml/components.drawio.png)
Теперь лучше?

2023-06-12 11:07 UTC, uncerso commented
> > Типичного пользователья нет. :(
> 
> А Роли и случаи использования не покрывают этот пункт?

Не-а. Типичный пользователь -- это некоторая усреднённая модель пользователя (по ролям, но тут интересен игрок в первую очередь). И с такой моделью среднестатистического пользователя проще работать. Поэтому в типичного пользователя придумывают как настоящего существующего человека: дают имя-фамилию, возраст, пол (если актуально), добавляют его "фотографию", придумывают его биографию (и что ещё может понадобиться). Но не просто воду льют, а пишут так, чтобы из такого описания делать выводы, в частности, почему его ваш продукт заинтересует и почему он им воспользуется. И из этого какие-то функциональные требования тоже могут появиться.

2023-06-12 11:16 UTC, uncerso commented on README.md
> +  анимаций и отрисовки кадров,
Вообще неочевидно, почему надо что-то рендерить просто потому-что TickEvent так самосгенерировался. 

Логично, чтобы кто-то попросил нарисовать следующий кадр (например, анимация пока не закончится должна делать такой запрос каждый кадр) или нажатие на кнопки клавиатуры. Ну и все эти запросы аккумулируются и выдают TickEvent не чаще, чем раз требуется для максимального fps.

2023-06-13 17:56 UTC, ProgMiner commented on README.md
> +- Система не должна воспроизводить звуки
Попытался исправить

2023-06-13 17:57 UTC, ProgMiner commented on README.md
> +- Должна быть доступна генерация случайного мира и загрузка из файла
Поправил. Требования про мобов пока не добавил, потому что это уже относится ко второй части реализации

2023-06-13 19:55 UTC, ProgMiner commented on README.md
> +
Не вполне понятно, в чём отличие Качественных характеристик от Нефункциональных требований. В лекции по диздоку из этих двух пунктов упомянут только первый и его содержимое описывается так, как я представляю себе Нефункциональные требования:

> качественные характеристики системы — сопровождаемость, расширяемость и т.п. Часто они конфликтуют друг с другом (например, погоня за скоростью работы может нанести серьёзный ущерб сопровождаемости). И именно качественные характеристики имеют решающее влияние на архитектуру. Если нужна максимальная производительность, будут использоваться совершенно другие архитектурные стили, языки и технологии, чем если нужна максимальная сопровождаемость или минимальный time-to-market.

2023-06-13 20:13 UTC, ProgMiner commented on README.md
> +  анимаций и отрисовки кадров,
Тут уж как сделал... Изначально планировалось, что примерно так и будет, как вы описываете, получилось что получилось. Всё таки "Разработка системы должна быть завершена к моменту сдачи экзамена (12.06.2023)", бизнес-требования не позволили продумать этот момент лучше

2023-06-13 23:26 UTC, ProgMiner commented
Исправил всё, о чём шла речь выше. Добавил недостающие разделы.

2023-06-17 15:31 UTC, uncerso approved these changes
Класс, что-то такое и хотелось увидеть. Зачёл.

2023-06-17 15:31 UTC, uncerso commented on README.md
> +себя в образе главного героя игры. Очень любит майнкрафт и мод Giselbaer's Durability Viewer.
Врядли, конечно, типичный игрок в вашу игру именно любил бы Giselbaer's Durability Viewer, но ладно, пусть. :)

2023-06-17 15:31 UTC, uncerso commented on README.md
> +все части системы.
В жизни, кстати, довольно мучительно отлаживать приложение с EventBus, ибо именно что буквально откуда угодно может прилететь событие, которое всё сломает.

2023-06-17 15:31 UTC, uncerso commented on README.md
> +![Диаграмма последовательности обработки события](./uml/event_propagation_sequence.drawio.png)
Когда нет возвращаемого значения (или оно в данном контексте бессмысленно), стрелочку возврата можно не рисовать.

2023-06-17 16:40 UTC, ProgMiner commented on README.md
> +себя в образе главного героя игры. Очень любит майнкрафт и мод Giselbaer's Durability Viewer.
Это была подвязка к тому, как выводится на экран текущая экипировка)

2023-06-17 16:41 UTC, ProgMiner commented on README.md
> +все части системы.
Это да. Но это всё ещё самый удобный и универсальный способ организации взаимодействия между всеми частями системы

2023-06-17 16:41 UTC, ProgMiner commented on README.md
> +![Диаграмма последовательности обработки события](./uml/event_propagation_sequence.drawio.png)
Спасибо, не знал

2023-06-18 12:30 UTC, merged